# Generated Python code
# Generated on: 2025-04-05 14:49:12
# This file was automatically generated by the compiler's code generator

import datetime
import sys
from dotenv import load_dotenv
import json
import os
import re
import requests

# Add the project root directory to sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..')))

from backend.llm_integration.gemini_helper import get_and_format_events
from backend.database.query import check_available_tickets, check_event_price, book_ticket, pay_booking, cancel_bookings

# Helper functions for ticket system operations
def check_availability(event_name, date):
    available = check_available_tickets(event_name, date)
    print(f"Available tickets for event {event_name}: {available}")
    return available

def check_price(event_name, date):
    price = check_event_price(event_name, date)
    if price:
        print(f"Price for event {event_name}: ${price:.2f}")
    else:
        print(f"Price information for event {event_name} not available.")
    return price

def book_tickets(quantity, user_id, date, event_name):
    success, bookMessage = book_ticket(quantity, user_id, date, event_name)
    return success, bookMessage

def pay_for_booking(event_name, user_name):
    success, payMessage = pay_booking(event_name, user_name)
    return success, payMessage

def cancel_booking(quantity, user_name, event_name):
    success, cancelMessage = cancel_bookings(quantity, user_name, event_name)
    return success, cancelMessage

def list_events_on_date(event_type: str, date_str: str) -> str:
    try:
        today = datetime.datetime.now().date()
        date_obj = datetime.datetime.strptime(date_str, '%B %d, %Y').date()
        if date_obj < today:
            return "Error: Cannot list events from the past"
        
        result = get_and_format_events(event_type=event_type, date=date_str)
        return result
    except ValueError:
        return "Error: Invalid date format. Use 'Month Day, Year'"

def list_event_details(event_name: str) -> str:
    result = get_and_format_events(event_name=event_name)
    return result if result else "No events found"

# Main program starts here


result = list_event_details("party")
print(result)

# By Alex-Ann Burrell :P
# == End of generated code == 